export const seafooddata = [{
    id :0 ,
    title: 'Fish Fry Recipe',
    imageUrl: 'https://i.ytimg.com/vi/30m3meOoxPE/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLA5anZ0pZ5XIaFsBd56ZrCvAYSkkw',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=30m3meOoxPE&t=82s',
  },
 { id : 1,
    title: 'Fish Curry ',
    imageUrl: 'https://i.ytimg.com/vi/vpFYuYdj5jk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLDWYiXS0uMfU0v7PTHBQmzMynPz_w',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=vpFYuYdj5jk&t=3s',
  },
  { 
  id :2 ,
    title: 'Banana Leaf Fish Fry ',
    imageUrl: 'https://i.ytimg.com/vi/2uQMxvg0yp0/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLA5U3Sqi9GrUr3AQPAkXQi8o10Hog',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=2uQMxvg0yp0',
  },
  { 
  id :3 ,
    title: 'Crab Fry',
    imageUrl: 'https://i.ytimg.com/vi/qOz2Y5GoU9k/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLDrxhOcdiOncrPFjtKFNzkJkEfuIg',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=qOz2Y5GoU9k',
  },
  { id :5 ,
  title: 'Mutton Kulambu In Tamil',
  imageUrl: 'https://i.ytimg.com/vi/p7oh-dCcalM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLA03ivUdIVObtNN8gyRT1bAVTszow',
  imageSize: 300,
  url:'https://www.youtube.com/watch?v=p7oh-dCcalM&t=15s',
},
{ 
id : 4,
    title: 'Prawn Curry',
    imageUrl: 'https://i.ytimg.com/vi/xkVxfZw0TIs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBm1Il3OSjprLe5b6zBzOnbh36vNQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=xkVxfZw0TIs',
  },
  { id :6 ,
  title: 'Mutton Biryani',
  imageUrl: 'https://i.ytimg.com/vi/7T3Rewqi8x8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCgNfSYELY9tAVjh3c--V85glY5rw',
  imageSize: 300,
  url:'https://www.youtube.com/watch?v=7T3Rewqi8x8&t=165s',
},
{ id :7 ,
title: 'Mutton Kurma Recipe',
imageUrl: 'https://i.ytimg.com/vi/3Dj9JpPh180/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLAVcG79CfnbBS3VJGS8esDLjNQAAw',
imageSize: 300,
url:'https://www.youtube.com/watch?v=3Dj9JpPh180&t=16s',
},
{ id : 8,
    title: 'Mutton Liver Fry recipe in Tamil',
    imageUrl: 'https://i.ytimg.com/vi/BuEeqctlkFc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCZ3wfyh_P-9AWTT0A72AP6cH7X0Q',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=BuEeqctlkFc&t=1s',
  },
  {  id :9 ,
    title: 'Traditional Mutton Biryani in Tamil',
    imageUrl: 'https://i.ytimg.com/vi/8Vws82O7uP0/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLA0rT0r40woB-4CEIA81TJ8xvoSRQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=8Vws82O7uP0&t=35s',
  },
]