export const vegdata = [{
    id : 0,
    title: 'Veg Biryani Recipe',
    imageUrl: 'https://i.ytimg.com/vi/bBSG089LBPo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLAbx8bGak7n7kbEIb__aRllln36ow',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=bBSG089LBPo&t=2s',
  },
  {
    id : 2,
    title: 'Gulkand Recipe',
    imageUrl: 'https://i.ytimg.com/vi/RZGpYvG9xz4/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCQdhCxBNi_pGy5r1cSV2gRZdc0tQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=RZGpYvG9xz4&t=67s',
  },
  {
    id : 3,
    title: 'Lunch Recipes ',
    imageUrl: 'https://i.ytimg.com/vi/6T7SeQ9g5cw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBbel8Dr3Cj2hR5rFQ9Dpzy2l4O-A',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=6T7SeQ9g5cw&t=13s',
  },
  {
    id : 4,
    title: 'Side Dish For Dosa ',
    imageUrl: 'https://i.ytimg.com/vi/sAZDstISB6g/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLA9d2vxPJdxAlhVYl8hqFI_9DfieQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=sAZDstISB6g&t=87s',
  },
  {
    id : 5,
    title: 'Healthy Breakfast',
    imageUrl: 'https://i.ytimg.com/vi/yC8DGIrncLs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLDGOHxzEhcGu80bfm3OvPoT5hP2Rw',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=yC8DGIrncLs',
  },
  {
    id : 6,
    title: 'Leftover Rice Recipes ',
    imageUrl: 'https://i.ytimg.com/vi/lUa_EjwjOp8/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBa6DkJ0rCRKvlun1Jv5kflZ0xkSQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=lUa_EjwjOp8&t=36s',
  },
  {
    id : 7,
    title: 'Ragi Recipes ',
    imageUrl: 'https://i.ytimg.com/vi/vhVLH76GeeA/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCZp4hGb5jdcqEdI5k98550FPGfhw',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=vhVLH76GeeA&t=141s',
  },
  {
    id : 8,
    title: 'Easy Snacks To Make At Home',
    imageUrl: 'https://i.ytimg.com/vi/yKi07vvTHPw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLDWGfbmnlHVA4iDaJ-9uR6gox-pOg',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=yKi07vvTHPw&t=5s',
  },
  {
    id : 9,
    title: 'Potato Recipes ',
    imageUrl: 'https://i.ytimg.com/vi/QovR0kK0IDQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLAPzmsaA86gGM6kz5A0OTw3XSte4Q',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=QovR0kK0IDQ&t=20s',
  },]
