export const chickendata = [{
    id : 0,
    title: 'Chicken 65',
    imageUrl: 'https://i.ytimg.com/vi/1nvPC94ampE/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLAj-Rg3WNLfyOsH6l8bJtcBzrOQPQ',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=1nvPC94ampE&t=1s',
  },
  {
    id : 1,
  title: 'Pepper Chicken Recipe',
    imageUrl: 'https://i.ytimg.com/vi/TKe7uJFT17s/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLB4Mz34VnYeQB',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=TKe7uJFT17s&t=25s',
  },
  {
    id : 2,
  title: 'Malai Chicken Tikka Recipe ',
    imageUrl: 'https://i.ytimg.com/vi/3Ho6htb8SfY/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLArmbpBJmu6rD09vdYLTsox',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=3Ho6htb8SfY&t=80s',
  },
  {
    id : 3,
  title: 'Chicken Varuval',
    imageUrl: 'https://i.ytimg.com/vi/oVSRrXs6OsQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBkeghiqTSW',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=oVSRrXs6OsQ&t=114s',
  },
  {
    id : 4,
  title: 'Chicken Biryani',
    imageUrl: 'https://i.ytimg.com/vi/WAjdjuHj8kg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCL8D',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=WAjdjuHj8kg&t=153s',
  },
  {
    id : 5,
  title: 'Chicken Salad Recipes',
    imageUrl: 'https://i.ytimg.com/vi/Z3hZPyit-Eo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLDpdr2h7Z9F0ei6ibBGJG9B',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=Z3hZPyit-Eo&t=2s',
  },
  {
    id : 6,
  title: 'Kadai Chicken Recipe',
    imageUrl: 'https://i.ytimg.com/vi/Y9uhn6RYL8E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLCipjY2Rn_2Lt9H7SHsqzbC_VGuSA"',
    imageSize: 300,
    url:'https://www.youtube.com/watch?v=Y9uhn6RYL8E&t=19s',
  },
  ]
